FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive
RUN echo "===> Installing system dependencies..." && \
  BUILD_DEPS="curl unzip" && \
  apt-get update && apt-get install --no-install-recommends -y \
  python3 python3-pip wget git \
  libappindicator3-1 libasound2 libdbus-glib-1-2 libxtst6 libxt6 firefox firefox-geckodriver \
  $BUILD_DEPS \
  xvfb

RUN echo "===> Installing geckodriver for firefox..." && \
  GECKODRIVER_VERSION=`curl -i https://github.com/mozilla/geckodriver/releases/latest | grep -Po 'v[0-9]+.[0-9]+.[0-9]+'` && \
  wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz && \
  tar -zxf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz -C /usr/local/bin && \
  chmod +x /usr/local/bin/geckodriver && \
  rm geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONUNBUFFERED=1

ENV APP_HOME /usr/src/app
WORKDIR /$APP_HOME

COPY *.py $APP_HOME/
COPY *.env $APP_HOME/
COPY requirements.txt $APP_HOME/

ADD data $APP_HOME/data
ADD cogs $APP_HOME/cogs

RUN pip install -r requirements.txt

CMD ["python3", "bot.py"]
